apiVersion: v1
kind: Pod
metadata:
  name: collector
spec:
  imagePullSecrets:
  - name: ghcr-secret
  containers:
  - name: collector
    image: ghcr.io/sammatime22/stockrate/collector:latest
    imagePullPolicy: Always
    resources:
      limits:
        ephemeral-storage: "1Gi"
    volumeMounts:
      - name: config-volume
        mountPath: /config-dir
  volumes:
    - name: config-volume
      configMap:
        name: collector-config