apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
  - name: database
    image: mariadb:latest
    ports:
    - containerPort: 3306
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: ....