apiVersion: v1
kind: Pod
metadata:
  name: distributor
spec:
  imagePullSecrets:
  - name: ghcr-secret
  containers:
  - name: distributor
    image: ghcr.io/sammatime22/stockrate/distributor:latest
    imagePullPolicy: Always
    resources:
      limits:
        ephemeral-storage: "1Gi"
    volumeMounts:
      - name: config-volume
        mountPath: /config-dir
  volumes:
    - name: config-volume
      configMap:
        name: distributor-config