apiVersion: v1
kind: Pod
metadata: 
  name: orchestrator
spec:
  containers:
  - name: orchestrator
    image: localhost/orchestrator:1.0.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        ephemeral-storage: "1Gi"