apiVersion: v1
kind: Service
metadata:
    name: matchadb-service
spec:
    selector:
        app: matchadb
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    type: ClusterIP