name: Publish Containers
on: 
  push:
    tags:
      - 'vlatest'


jobs:
  publish-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Images for All StockRate Projects
        run: |
          cd Collector
          docker build . -t ghcr.io/sammatime22/Stockrate/collector:latest
          docker push ghcr.io/sammatime22/Stockrate/collector:latest
          cd ../Distributor
          docker build . -t ghcr.io/sammatime22/Stockrate/distributor:latest
          docker push ghcr.io/sammatime22/Stockrate/distributor:latest
          cd ../Factory
          docker build . -t ghcr.io/sammatime22/Stockrate/factory:latest
          docker push ghcr.io/sammatime22/Stockrate/factory:latest
          cd ../Orchestrator
          docker build . -t ghcr.io/sammatime22/Stockrate/orchestrator:latest
          docker push ghcr.io/sammatime22/Stockrate/orchestrator:latest
