name: Publish Containers
on: 
  push:
    tags:
      - '*'


jobs:
  publish-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Images for All StockRate Projects
        run: |
          cd Factory
          docker build . -t ghcr.io/sammatime22/stockrate/factory:${{ github.ref_name }}
          docker push ghcr.io/sammatime22/stockrate/factory:${{ github.ref_name }}
          cd ../Collector
          docker build . -t ghcr.io/sammatime22/stockrate/collector:${{ github.ref_name }}
          docker push ghcr.io/sammatime22/stockrate/collector:${{ github.ref_name }}
          cd ../Distributor
          docker build . -t ghcr.io/sammatime22/stockrate/distributor:${{ github.ref_name }}
          docker push ghcr.io/sammatime22/stockrate/distributor:${{ github.ref_name }}
          cd ../Orchestrator
          docker build . -t ghcr.io/sammatime22/stockrate/orchestrator:${{ github.ref_name }}
          docker push ghcr.io/sammatime22/stockrate/orchestrator:${{ github.ref_name }}
